// <auto-generated />
namespace CCG.WebAPI.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmenus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmenus));
        
        string IMigrationMetadata.Id
        {
            get { return "201506160242285_addmenus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
